In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("crime_dataset_india.csv")
df.drop_duplicates(inplace=True)
df.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
0,1,02-01-2020 00:00,01-01-2020 00:00,01-01-2020 01:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
1,2,01-01-2020 19:00,01-01-2020 01:00,01-01-2020 06:26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaN
2,3,02-01-2020 05:00,01-01-2020 02:00,01-01-2020 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
3,4,01-01-2020 05:00,01-01-2020 03:00,01-01-2020 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 05:00
4,5,01-01-2020 21:00,01-01-2020 04:00,01-01-2020 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21:00

In [ ]:
df.shape

(40160, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Report Number       40160 non-null  int64
 1   Date Reported       40160 non-null  object
 2   Date of Occurrence  40160 non-null  object
 3   Time of Occurrence  40160 non-null  object
 4   City                40160 non-null  object
 5   Crime Code          40160 non-null  int64
 6   Crime Description   40160 non-null  object
 7   Victim Age          40160 non-null  int64
 8   Victim Gender       40160 non-null  object
 9   Weapon Used         34370 non-null  object
 10  Crime Domain        40160 non-null  object
 11  Police Deployed     40160 non-null  int64
 12  Case Closed         40160 non-null  object
 13  Date Case Closed    20062 non-null  object
dtypes: int64(4), object(10)
memory usage: 4.3+ MB

In [ ]:
df.isnull().sum()

Report Number             0
Date Reported             0
Date of Occurrence        0
Time of Occurrence        0
City                      0
Crime Code                0
Crime Description         0
Victim Age                0
Victim Gender             0
Weapon Used            5790
Crime Domain              0
Police Deployed           0
Case Closed               0
Date Case Closed      20098
dtype: int64

In [ ]:
df.describe(include='all')

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
count,40160.000000,40160,40160,40160,40160,40160.000000,40160,40160.00000,40160,34370,40160,40160.000000,40160,20062
unique,NaN,25546,40160,39886,29,NaN,21,NaN,3,6,4,NaN,2,16011
top,NaN,03-01-2022 20:00,07-30-2024 15:00,14-10-2022 06:54,Delhi,NaN,BURGLARY,NaN,F,Knife,Other Crime,NaN,No,04-05-2024 18:00
freq,NaN,7,1,3,5400,NaN,1980,NaN,22423,5835,22948,NaN,20098,6
mean,20080.500000,NaN,NaN,NaN,NaN,349.360259,NaN,44.49126,NaN,NaN,NaN,10.006250,NaN,NaN
std,11593.337742,NaN,NaN,NaN,NaN,144.169205,NaN,20.22555,NaN,NaN,NaN,5.467951,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,100.000000,NaN,10.00000,NaN,NaN,NaN,1.000000,NaN,NaN
25%,10040.750000,NaN,NaN,NaN,NaN,225.000000,NaN,27.00000,NaN,NaN,NaN,5.000000,NaN,NaN
50%,20080.500000,NaN,NaN,NaN,NaN,349.000000,NaN,44.00000,NaN,NaN,NaN,10.000000,NaN,NaN
75%,30120.250000,NaN,NaN,NaN,NaN,474.000000,NaN,62.00000,NaN,NaN,NaN,15.000000,NaN,NaN
max,40160.000000,NaN,NaN,NaN,NaN,599.000000,NaN,79.00000,NaN,NaN,NaN,19.000000,NaN,NaN

In [ ]:
df["Date of Occurrence"]=pd.to_datetime(df["Date of Occurrence"],errors="coerce",format="mixed")
df["Date Reported"]=pd.to_datetime(df["Date Reported"],errors="coerce",format="mixed")
df["Time of Occurrence"]=pd.to_datetime(df["Time of Occurrence"],errors="coerce",format="mixed")
df["Date Case Closed"]=pd.to_datetime(df["Date Case Closed"],errors="coerce",format="mixed")

In [ ]:
df["Year"]=df["Date of Occurrence"].dt.year
df["Month"]=df["Date of Occurrence"].dt.month
df["Hour"]=df["Time of Occurrence"].dt.hour
df["Case Duration"]=(df["Date Case Closed"]-df["Date Reported"]).dt.days

In [ ]:
df["Weapon Used"]=df["Weapon Used"].fillna("Unknown")
df["Case Status"]=df["Date Case Closed"].apply(lambda x:"Open" if pd.isna(x) else "Closed")

In [ ]:
def age_group(age):
  if age<18:
    return "Teen"
  elif age<35:
    return "Young Adult"
  elif age<60:
    return "Adult"
  else:
    return "Senior"

df["Age Group"]=df["Victim Age"].apply(age_group)

In [ ]:
def time_peroid(hour):
  if hour<6:
    return "Late Night"
  elif hour<12:
    return "Morning"
  elif hour<18:
    return "Afternoon"
  else:
    return "Night"

df["time_peroid"]=df["Hour"].apply(time_peroid)

In [ ]:
df["Crime Description"].unique()

array(['IDENTITY THEFT', 'HOMICIDE', 'KIDNAPPING', 'BURGLARY',
       'VANDALISM', 'ASSAULT', 'VEHICLE - STOLEN', 'COUNTERFEITING',
       'EXTORTION', 'PUBLIC INTOXICATION', 'FRAUD', 'SEXUAL ASSAULT',
       'DRUG OFFENSE', 'ARSON', 'CYBERCRIME', 'TRAFFIC VIOLATION',
       'SHOPLIFTING', 'ILLEGAL POSSESSION', 'FIREARM OFFENSE', 'ROBBERY',
       'DOMESTIC VIOLENCE'], dtype=object)

In [ ]:
def severity(crime):
  high=[
      'HOMICIDE','SEXUAL ASSAULT','KIDNAPPING','DOMESTIC VIOLENCE',
      'FIREARM OFFENSE'
  ]
  medium=[
     'ASSAULT','ROBBERY','BURGLARY','ARSON','EXTORTION','VEHICLE - STOLEN',
     'DRUG OFFENSE'
  ]
  if crime in high:
    return "High"
  elif crime in medium:
    return "Medium"
  else:
    return "Low"

df["Crime Severity"]=df["Crime Description"].apply(severity)

In [ ]:
def closure_speed(days):
  if pd.isna(days):
    return "Open"
  elif days<=30:
    return "Fast"
  elif days<=90:
    return "Average"
  else:
    return "Slow"
df["Closure Speed"]=df["Case Duration"].apply(closure_speed)

In [ ]:
city_score=df.groupby("City")["Report Number"].count().reset_index()
city_score.columns=["city","crime_count"]
city_score.head()

        city  crime_count
0       Agra          764
1  Ahmedabad         1817
2  Bangalore         3588
3     Bhopal          690
4    Chennai         2493

In [ ]:
city_score["risk_score"]=(
    city_score["crime_count"]/city_score["crime_count"].max()
)*100

In [ ]:
def risk_category(score):
  if score>=75:
    return "High Risk"
  elif score>=40:
    return "Medium Risk"
  else:
    return "Low Risk"
city_score["risk_category"]=city_score["risk_score"].apply(risk_category)

In [ ]:
city_score.head()

        city  crime_count  risk_score risk_category
0       Agra          764   14.148148      Low Risk
1  Ahmedabad         1817   33.648148      Low Risk
2  Bangalore         3588   66.444444   Medium Risk
3     Bhopal          690   12.777778      Low Risk
4    Chennai         2493   46.166667   Medium Risk

In [ ]:
df=df.merge(
    city_score[["city","risk_score","risk_category"]],
    left_on='City',
    right_on='city',
    how='left'
)

In [ ]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [ ]:
df.columns

Index(['report_number', 'date_reported', 'date_of_occurrence',
       'time_of_occurrence', 'city', 'crime_code', 'crime_description',
       'victim_age', 'victim_gender', 'weapon_used', 'crime_domain',
       'police_deployed', 'case_closed', 'date_case_closed', 'year', 'month',
       'hour', 'case_duration', 'case_status', 'age_group', 'time_peroid',
       'crime_severity', 'closure_speed', 'city', 'risk_score',
       'risk_category'],
      dtype='object')

In [ ]:
df.isnull().sum()

report_number             0
date_reported             0
date_of_occurrence        0
time_of_occurrence        0
city                      0
crime_code                0
crime_description         0
victim_age                0
victim_gender             0
weapon_used               0
crime_domain              0
police_deployed           0
case_closed               0
date_case_closed      20098
year                      0
month                     0
hour                      0
case_duration         20098
case_status               0
age_group                 0
time_peroid               0
crime_severity            0
closure_speed             0
city                      0
risk_score                0
risk_category             0
dtype: int64

In [ ]:
df.rename(
    columns={"time_peroid":"time_period"},
    inplace=True
)

In [ ]:
df.to_csv("crime_analysis_final.csv",index=False)